server {
    listen 80;

    # Where the React app is built
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Routes to index.html for React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Error pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
